Repository nbc-6candoit/react-dlive, pull requests merged in 2023-12, with the labels that each got.

#5 style: Header UI setting (#3)
  src/assets/img/dlivelogo.png
  src/components/Header.jsx
  src/pages/Spot.jsx
  src/shared/Router.jsx
Labels: UI

#7 에스코어드림 웹폰트 적용 (#6)
  public/index.html
  src/GlobalStyles.js
  src/pages/Log.jsx
Labels: UI

#11 add: 차박로그 카드 컴포넌트 생성
  package.json
  src/assets/img/avatar.png
  src/components/Header.jsx
  src/components/SpotInfo.jsx
  src/components/SpotLog.jsx
  src/components/common/Avatar.jsx
  src/components/common/LogCard.jsx
  src/components/common/Tag.jsx
  src/pages/Spot.jsx
  yarn.lock
Labels: 수정, UI

#16 [feature/AddLogForm] 차박로그 등록페이지, 등록폼
  .env .local
  package-lock.json
  package.json
  src/assets/img/spot_thumbnail.jpg
  src/components/AddLogForm/AddLogForm.jsx
  src/pages/AddLog.jsx
  src/pages/Log.jsx
  yarn.lock
Labels: 기능, UI

#22 [Feature/addSpot] 차박명소 등록 페이지 UI 구현
  package.json
  public/index.html
  src/components/AddLogForm/AddLogForm.jsx
  src/components/Home/body.jsx
  src/components/NavBar.jsx
  src/components/SpotDetail/SpotInfo.jsx
  src/components/SpotDetail/SpotLog.jsx
  src/components/common/Button.jsx
  src/components/common/Tag.jsx
  src/pages/AddSpot.jsx
  src/pages/Spot.jsx
  yarn.lock
Labels: 수정, UI

#29 [Feature/addSpot] 차박명소 등록페이지 지도 API 기능 구현
  package.json
  public/index.html
  src/components/Home/Map/Map.jsx
  src/components/NavBar.jsx
  src/components/common/Button.jsx
  src/components/common/Tag.jsx
  src/components/naverMap/GeocoderMap.jsx
  src/pages/AddSpot.jsx
  src/redux/config/configStore.js
  src/redux/modules/currentLocationSlice.js
  yarn.lock
Labels: 기능, UI

#32 [feature/MainLogList] main 페이지에 차박로그 리스트
  public/index.html
  src/GlobalStyles.js
  src/components/AddLogForm/AddLogForm.jsx
  src/components/Home/body.jsx
  src/components/NavBar.jsx
  src/components/SpotDetail/SpotLog.jsx
  src/components/common/Avatar.jsx
  src/components/common/LogCard.jsx
  src/fonts.css
  src/index.js
  src/pages/Log.jsx
  src/redux/config/configStore.js
  src/redux/modules/logSlice.js
  src/redux/modules/logsSlice.js
  src/shared/Router.jsx
  yarn.lock
Labels: 기능, UI

#35 [Feature/detail spot] 차박명소 상세페이지 기능구현 및 UI 수정
  src/api/spot.js
  src/components/Home/HotSpotList.jsx
  src/components/Home/body.jsx
  src/components/Home/slide/Slide.jsx
  src/components/NavBar.jsx
  src/components/SpotDetail/SpotInfo.jsx
  src/components/SpotDetail/SpotLog.jsx
  src/components/addSpot/FacilitiesIcons.jsx
  src/components/addSpot/TagSelection.jsx
  src/components/common/Tag.jsx
  src/components/naverMap/GeocoderMap.jsx
  src/constants/spotOptions.js
  src/hooks/useClickedState.js
  src/hooks/useImageUploader.js
  src/hooks/useInput.js
  src/pages/AddSpot.jsx
  src/pages/Spot.jsx
  src/redux/config/configStore.js
  src/redux/modules/spotDataSlice.js
  src/redux/modules/spotSlice.js
  src/shared/Router.jsx
Labels: 기능, UI

#38 [Feature/UI] 메인페이지 더보기버튼 및 디테일페이지 무한스크롤 구현
  src/components/Home/HotSpotList.jsx
  src/components/Home/body.jsx
  src/components/SpotDetail/SpotInfo.jsx
  src/components/SpotDetail/SpotLog.jsx
  src/components/common/LogCard.jsx
  src/components/naverMap/GeocoderMap.jsx
  src/pages/Main.jsx
  src/pages/SpotDetail.jsx
  src/shared/Router.jsx
Labels: 기능, UI
