Repository nbc-6candoit/react-dlive, pull requests merged in 2024-01, with the labels that each got.

#47 update: 로그인상태 유지 및 접근권한 (#46)
  .env
  src/App.js
  src/components/Home/slide/Slide.jsx
  src/components/NavBar.jsx
  src/pages/AddSpot.jsx
  src/pages/Login.jsx
  src/redux/modules/authSlice.js
  src/shared/PrivateRoute.js
  src/shared/Router.jsx
  src/shared/firebase.js
  yarn.lock
Labels: 기능

#49 [feature/MainLogList] 메인로그리스트 3개만 노출, form react-hook-form 라이브러리 적용
  package-lock.json
  package.json
  src/App.js
  src/components/AddLogForm/AddLogForm.jsx
  src/components/SpotDetail/SpotLog.jsx
  src/components/common/LogCard.jsx
  src/pages/SpotDetail.jsx
  src/shared/Router.jsx
  yarn.lock
Labels: 기능, UI

#50 [jiyeon] 이미지 유무 조건 추가
  src/components/common/LogCard.jsx
  src/shared/PrivateRoute.js
Labels: 수정

#52 [Feature/login_setting] 차박로그, 차박명소 데이터 연결
  .env
  package.json
  src/App.js
  src/components/AddLogForm/AddLogForm.jsx
  src/components/SpotDetail/SpotLog.jsx
  src/components/common/LogCard.jsx
  src/pages/AddSpot.jsx
  src/pages/Log.jsx
  src/pages/Spot.jsx
  src/redux/modules/logSlice.js
  src/shared/PrivateRoute.js
  src/shared/Router.jsx
Labels: 기능

#53 디자인 수정
  src/GlobalStyles.js
  src/assets/img/강2.png
  src/assets/img/바다2.png
  src/assets/img/산2.png
  src/components/AddLogForm/AddLogForm.jsx
  src/components/Footer.jsx
  src/components/Header.jsx
  src/components/Home/HotSpotList.jsx
  src/components/Home/body.jsx
  src/components/Home/slide/Slide.jsx
  src/components/Home/viewDetail/Mountains.jsx
  src/components/Home/viewDetail/Ocean.jsx
  src/components/Home/viewDetail/River.jsx
  src/components/NavBar.jsx
  src/components/SpotDetail/SpotInfo.jsx
  src/components/SpotDetail/SpotLog.jsx
  src/components/common/Button.jsx
  src/components/common/LogCard.jsx
  src/components/naverMap/GeocoderMap.jsx
  src/fonts.css
  src/pages/AddSpot.jsx
  src/pages/InfoFix.jsx
  src/pages/Log.jsx
  src/pages/Login.jsx
  src/pages/Main.jsx
  src/pages/Mypage.jsx
  src/pages/Spot.jsx
  src/pages/SpotDetail.jsx
Labels: 수정, UI

#55 디자인 및 더보기 버튼 수정 등
  src/components/AddLogForm/AddLogForm.jsx
  src/components/Home/body.jsx
  src/pages/InfoFix.jsx
  src/pages/SpotDetail.jsx
Labels: 수정, UI
